name: Christian Sika
favicon: null
layout_spectrum: 0.36836
typography_spectrum: 0.50137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363636'
    - '#b1aca6'
    - '#565553'
    - '#e0dbd5'
    - '#1d1d1d'
  brandStrength: 0.7863789808470756
  lightness: 0.5116267551202327
  saturation: 0.579602736281231
  rhythmicContrast: 1
purpose: []
