name: Christian Sika
analytics: {}
purpose: []
github: true
cta:
  bucket: null
  version: null
  domain: null
author:
  name: christian sika
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
navigation:
  - name: Christian Sika
    id: af01c375-0442-459d-ab59-155f83b24bb8
    type: content
layout_spectrum: 0.36836
color:
  lightness: 0.5116267551202327
  brandColors:
    - '#363636'
    - '#b1aca6'
    - '#565553'
    - '#e0dbd5'
    - '#1d1d1d'
  saturation: 0.579602736281231
  brandStrength: 0.7863789808470756
  rhythmicContrast: 1
content_rating:
  adult: false
typography_spectrum: 0.50137
opengraph: {}
title: senior ux designer
description: The grid blows
